Repository Orange-OpenSource/nifikop, pull requests merged in 2020-08, with the labels that each got.

#24 [Fix/Documentation] Pattern & versions
  CHANGELOG.md
  Makefile
  config/samples/simplenificluster.yaml
  config/samples/tls_secured_nificluster.yaml
  docs/tutorials/secured_nifi_cluster_on_gcp/kubernetes/nifi/secured_nifi_cluster.yaml
  docs/tutorials/secured_nifi_cluster_on_gcp_with_external_dns/kubernetes/nifi/secured_nifi_cluster.yaml
  website/docs/3_tasks/2_security/2_authentication/1_oidc.md
  website/docs/6_contributing/1_developer_guide.md
Labels: bug, documentation

#25 [Feature/Chart] Quick fix for supporting watching multiple namespaces
  CHANGELOG.md
  helm/nifikop/templates/deployment.yaml
  helm/nifikop/templates/role.yaml
  helm/nifikop/templates/role_binding.yaml
  helm/nifikop/values.yaml
Labels: community, enhancement, priority:1

#28 [Fix/Operator] PKI Finalizer namespace
  CHANGELOG.md
  pkg/pki/certmanagerpki/certmanager.go
  pkg/pki/certmanagerpki/certmanager_pki.go
Labels: MVP, bug, priority:1

#29 [Version/Operator] Bump version to 0.2.1
  CHANGELOG.md
  deploy/operator.yaml
  helm/nifikop/Chart.yaml
  helm/nifikop/README.md
  helm/nifikop/values.yaml
  version/version.go
  website/blog/2020-06-30-secured_nifi_cluster_on_gcp_with_external_dns.md
  website/docs/2_setup/3_install/1_customizable_install_with_helm.md
  website/docs/6_contributing/1_developer_guide.md
Labels: priority:1

#30 [Fix/Documentation] slack link
  CHANGELOG.md
  README.md
Labels: MVP, bug, documentation, priority:1
