Repository Orange-OpenSource/nifikop, pull requests merged in 2021-05, with the labels that each got.

#98 [Feature/Operator] Add empty_dir volume for /tmp dir
  CHANGELOG.md
  pkg/resources/nifi/nifi.go
  pkg/resources/nifi/pod.go
Labels: MVP, enhancement, priority:1

#93 included securityContext in helm chart
  helm/nifikop/templates/deployment.yaml
  helm/nifikop/templates/service_account.yaml
  helm/nifikop/values.yaml
Labels: MVP, community, enhancement, priority:2

#102 fix documentation
  site/docs/3_tasks/2_security/1_ssl.md
  site/website/versioned_docs/version-v0.4.3/3_tasks/2_security/1_ssl.md
  site/website/versioned_docs/version-v0.5.3/3_tasks/2_security/1_ssl.md
  site/website/versioned_docs/version-v0.6.0/3_tasks/2_security/1_ssl.md
  site/website/versioned_docs/version-v0.6.1/3_tasks/2_security/1_ssl.md
Labels: MVP, bug, documentation, priority:1
